# Generated by Django 2.2.16 on 2020-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='cdcd', max_length=255),
            preserve_default=False,
        ),
    ]
